version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./logs/nginx:/var/log/nginx
            - ./public:/var/www/public:ro

    php-fpm:
        build: ./services/php-fpm
        restart: always
        volumes:
            - ./services/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./services/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
            - ./logs/php-fpm:/var/log/php-fpm
            - ./public:/var/www/public:ro
            - ./src:/var/www/src:ro
