version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./logs/nginx:/var/log/nginx
            - ./public:/var/www/public:ro

    php-fpm:
        build: ./services/php-fpm
        restart: always
        volumes:
            - ./services/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./services/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
            - ./logs/php-fpm:/var/log/php-fpm
            - ./public:/var/www/public:ro
            - ./src:/var/www/src:ro
            - ./.env:/var/www/.env:ro
    mariadb:
        image: mariadb:latest
        restart: always
        container_name: ${MYSQL_HOST}
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./data/mariadb/mysql:/var/lib/mysql
            - ./data/mariadb/initial-data:/docker-entrypoint-initdb.d:ro

    mailcatcher:
        image: sj26/mailcatcher:latest
        restart: always
        container_name: ${SMTP_HOST}
        ports:
            - "1025:1025"
            - "1080:1080"
